/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.amf.event.monitor.s.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AMFEvent service. Represents a row in the &quot;AMF_AMFEvent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.amf.event.monitor.s.model.impl.AMFEventModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.amf.event.monitor.s.model.impl.AMFEventImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AMFEvent
 * @generated
 */
@ProviderType
public interface AMFEventModel extends BaseModel<AMFEvent> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a amf event model instance should use the {@link AMFEvent} interface instead.
	 */

	/**
	 * Returns the primary key of this amf event.
	 *
	 * @return the primary key of this amf event
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this amf event.
	 *
	 * @param primaryKey the primary key of this amf event
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this amf event.
	 *
	 * @return the uuid of this amf event
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this amf event.
	 *
	 * @param uuid the uuid of this amf event
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the audit event ID of this amf event.
	 *
	 * @return the audit event ID of this amf event
	 */
	public long getAuditEventId();

	/**
	 * Sets the audit event ID of this amf event.
	 *
	 * @param auditEventId the audit event ID of this amf event
	 */
	public void setAuditEventId(long auditEventId);

	/**
	 * Returns the user ID of this amf event.
	 *
	 * @return the user ID of this amf event
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this amf event.
	 *
	 * @param userId the user ID of this amf event
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this amf event.
	 *
	 * @return the user uuid of this amf event
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this amf event.
	 *
	 * @param userUuid the user uuid of this amf event
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the username of this amf event.
	 *
	 * @return the username of this amf event
	 */
	@AutoEscape
	public String getUsername();

	/**
	 * Sets the username of this amf event.
	 *
	 * @param username the username of this amf event
	 */
	public void setUsername(String username);

	/**
	 * Returns the create date of this amf event.
	 *
	 * @return the create date of this amf event
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this amf event.
	 *
	 * @param createDate the create date of this amf event
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the event type of this amf event.
	 *
	 * @return the event type of this amf event
	 */
	@AutoEscape
	public String getEventType();

	/**
	 * Sets the event type of this amf event.
	 *
	 * @param eventType the event type of this amf event
	 */
	public void setEventType(String eventType);

	/**
	 * Returns the client ip of this amf event.
	 *
	 * @return the client ip of this amf event
	 */
	@AutoEscape
	public String getClientIp();

	/**
	 * Sets the client ip of this amf event.
	 *
	 * @param clientIp the client ip of this amf event
	 */
	public void setClientIp(String clientIp);

}