/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.amf.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AMFUser service. Represents a row in the &quot;AMFUR_AMFUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.docs.amf.registration.model.impl.AMFUserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.docs.amf.registration.model.impl.AMFUserImpl</code>.
 * </p>
 *
 * @author liferay
 * @see AMFUser
 * @generated
 */
@ProviderType
public interface AMFUserModel extends BaseModel<AMFUser>, MVCCModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a amf user model instance should use the {@link AMFUser} interface instead.
	 */

	/**
	 * Returns the primary key of this amf user.
	 *
	 * @return the primary key of this amf user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this amf user.
	 *
	 * @param primaryKey the primary key of this amf user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this amf user.
	 *
	 * @return the mvcc version of this amf user
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this amf user.
	 *
	 * @param mvccVersion the mvcc version of this amf user
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this amf user.
	 *
	 * @return the uuid of this amf user
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this amf user.
	 *
	 * @param uuid the uuid of this amf user
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the user ID of this amf user.
	 *
	 * @return the user ID of this amf user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this amf user.
	 *
	 * @param userId the user ID of this amf user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this amf user.
	 *
	 * @return the user uuid of this amf user
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this amf user.
	 *
	 * @param userUuid the user uuid of this amf user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the male of this amf user.
	 *
	 * @return the male of this amf user
	 */
	public Boolean getMale();

	/**
	 * Sets the male of this amf user.
	 *
	 * @param male the male of this amf user
	 */
	public void setMale(Boolean male);

	/**
	 * Returns the dob of this amf user.
	 *
	 * @return the dob of this amf user
	 */
	public Date getDob();

	/**
	 * Sets the dob of this amf user.
	 *
	 * @param dob the dob of this amf user
	 */
	public void setDob(Date dob);

	/**
	 * Returns the home phone of this amf user.
	 *
	 * @return the home phone of this amf user
	 */
	@AutoEscape
	public String getHomePhone();

	/**
	 * Sets the home phone of this amf user.
	 *
	 * @param homePhone the home phone of this amf user
	 */
	public void setHomePhone(String homePhone);

	/**
	 * Returns the mobile phone of this amf user.
	 *
	 * @return the mobile phone of this amf user
	 */
	@AutoEscape
	public String getMobilePhone();

	/**
	 * Sets the mobile phone of this amf user.
	 *
	 * @param mobilePhone the mobile phone of this amf user
	 */
	public void setMobilePhone(String mobilePhone);

	/**
	 * Returns the address of this amf user.
	 *
	 * @return the address of this amf user
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this amf user.
	 *
	 * @param address the address of this amf user
	 */
	public void setAddress(String address);

	/**
	 * Returns the address2 of this amf user.
	 *
	 * @return the address2 of this amf user
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this amf user.
	 *
	 * @param address2 the address2 of this amf user
	 */
	public void setAddress2(String address2);

	/**
	 * Returns the city of this amf user.
	 *
	 * @return the city of this amf user
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this amf user.
	 *
	 * @param city the city of this amf user
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this amf user.
	 *
	 * @return the state of this amf user
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this amf user.
	 *
	 * @param state the state of this amf user
	 */
	public void setState(String state);

	/**
	 * Returns the zip of this amf user.
	 *
	 * @return the zip of this amf user
	 */
	@AutoEscape
	public String getZip();

	/**
	 * Sets the zip of this amf user.
	 *
	 * @param zip the zip of this amf user
	 */
	public void setZip(String zip);

	/**
	 * Returns the create date of this amf user.
	 *
	 * @return the create date of this amf user
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this amf user.
	 *
	 * @param createDate the create date of this amf user
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this amf user.
	 *
	 * @return the modified date of this amf user
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this amf user.
	 *
	 * @param modifiedDate the modified date of this amf user
	 */
	public void setModifiedDate(Date modifiedDate);

}